store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login, name='login'),
    
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

store/models.py
from django.db import models
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

# Create your models here.


SUBJECT_CHOICES = [
    ('Questions', 'Questions'),
    ('Book Consulation', 'Book Consulation'),
    ('Request More Reviews', 'Request More Reviews'),
    ('Contact a Specialist', 'Contact a Specialist'),
    ('Bussiness Inquery', 'Bussiness Inquery')
   

]

class Contact(models.Model):
    name = models.CharField(max_length=50)
    subject = models.CharField(max_length=50, choices=SUBJECT_CHOICES)
    sender = models.EmailField()

    def __str__(self):
        return self.name



class ContactForm(ModelForm):
    class Meta:
        model= Contact
        fields = ('name', 'subject', 'sender')
        
        help_texts = {
            'sender':_('We will contact you soon'),
        }
        error_messages = {
            'name': {
                'max_length':_("Just you first name will suffice!"),
            },
        }

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# from .models import Contact
from django.forms import ModelForm


# class SignUpForm(UserCreationForm):
#     first_name = forms.CharField(max_length=30)
#     last_name = forms.CharField(max_length=30)
#     email = forms.EmailField(max_length=254)

#     class Meta:
#         model = User
#         fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

#     def save(self, commit=True):
#         # Save the provided password in hashed format
#         user = super(SignUpForm, self).save(commit=False)
#         user.username(self.cleaned_data['username'])
#         user.email(self.cleaned_data['email'])
#         user.set_password(self.cleaned_data["password1"])
#         if commit:
#             user.save()
#         return user


# class SignUpForm()

class LoginForm(forms.Form):
    username = forms.CharField()
    # typically used on senstieve data
    password = forms.CharField(
        widget=forms.PasswordInput
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")



    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)
        if not qs.exists():
            raise forms.ValidationError("This is an invalid error")

        return username



# class SignUpForm(forms.Form):
#     username = forms.CharField()
#     email = forms.EmailField()
#     password1 = forms.CharField(label='Password')
#     password2 = forms.CharField(label='Confirm Password')

#     def clean_username(self):
#         username = self.cleaned_data.get("username")
#         qs = User.objects.filter(username__iexact=username)
#         # qs.save()
#         if qs.exists():
#             raise forms.ValidationError("This is an invalid username")

#         return username

#     def clean_email(self):
#         email = self.cleaned_data.get("email")
#         qs = User.objects.filter(email__iexact=email)
#         # qs.save()
#         if qs.exists():
#             raise forms.ValidationError("This is an invalid email")

#         return email

    # def save(self, *args, **kwargs):
    #     u = self.instance.user
    #     u.first_name = self.cleaned_data['username']
    #     u.last_name = self.cleaned_data['password1']
    #     u.save()
    #     return super(SignUpForm, self).save(*args, **kwargs)



class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

store/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
# from .forms import SignUpForm
from django.core.mail import send_mail
from django.urls import reverse
from django.http import HttpResponseRedirect
# from .models import Contact, ContactForm, Blog
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, SignUpForm
from .models import Contact, ContactForm

User = get_user_model()

def index(request):
    context = {}
    return render(request, 'store/index.html', context)

# def login(request):
#     form = LoginForm(request.POST or None)
#     if form.is_valid():
#         username = form.cleaned_data.get("username")
#         password = form.cleaned_data.get("password")

#         user = authenticate(request, username=username, password=password)
#         if user == None:
#             # attempt = request.session.get("attemplt") or 0
#             # request.session['attempt'] += 1
#             request.session['invalid_user'] = 1
#             return render(request, "try/login.html", {"form": form})
#         auth_login(request, user)
#         return HttpResponseRedirect('/dashboard/')

    
#     return render(request, 'try/login.html', {"form": form})


def aboutus(request):
    context = {}
    return render(request, 'store/about-us.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()
            # some sort of action needs to be performed here
            # (1) save data
            # (2) send an email ####
            # (3) return search result
            # (4) upload a file
            return HttpResponseRedirect(reverse('aboutus'))
    else:
        form = ContactForm()
    context = {}
    return render(request, 'store/contact.html', context)



def login(request):
    context = {}
    if request.user.is_authenticated:
        return redirect('/dashboard/')
    else:

        # form = AuthenticationForm()
    
        if request.method == 'POST':

            username = request.POST.get('username')
            password = request.POST.get('password')
            # check if user is in database
            user = authenticate(username=username, password=password)

            if user is not None:
                auth_login(request, user)
                return redirect('/dashboard/')
            else:
                messages.info(request, "username or password is incorrect")
       
    return render(request, 'store/login.html', context)




# def signup(request):
#     form = SignUpForm(request.POST or None)
#     if form.is_valid():
        
#         print("is valid")
#         username = form.cleaned_data.get("username")
#         email = form.cleaned_data.get("email")
#         password = form.cleaned_data.get("password1")
#         password2 = form.cleaned_data.get("password2")
#         try:
#             user = User.objects.create_user(username, email, password)
#             form.save()
#         except:
#             user = None

#         if user != None:
#             auth_login(request, user)
#             form.save()
#             # form.save(commit=false)  
            
#             # attempt = request.session.get("attemplt") or 0
#             # request.session['attempt'] += 1
            
#             return HttpResponseRedirect('/dashboard/')
#         else:
#             request.session['register_error'] = 1
     

    
#     return render(request, 'try/login.html', {"form": form})



def signup(request):
    if request.user.is_authenticated:
        return redirect('/dashboard/')
    else:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                auth_login(request, user)
                return HttpResponseRedirect(reverse('dashboard'))
        else:
            form = SignUpForm
            context = {}
    return render(request, 'store/register.html', {})



    

@login_required(login_url='/login/')
def dashboard(request):
    if request.method == 'POST':
        auth_logout(request)

        return redirect('/login/')
    context = {}
    return render(request, 'store/dashboard.html', context)

store/templates/store/about-us.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}


<!-- the main banner with our story section -->
<div class="this-is-our-story">
    <div class="small-container center-items about">
        <div class="col-about-3">
            <h1>Our Story</h1>
            <div class="short-summ">
                <p>When I began this company it was just me and my husband. We had full time jobs so it was kinda like our side hustle. After I was diagnosed with a serious disease I was determined to heal myself naturally. After receiving several certifications in nutrition, I decided to try and help others. Thank you for being part of our story. We believe that everyone should Eat To Heal.</p>
            </div>
        </div>

        <div class="col-about-3">
            <h1>Our Future</h1>
            <div class="short-summ">
                <p>We are planning on making great strides in the future by opening our own product line up. Our products will include vitamins, alkeizar water, and protein powerders. We will stand by our belifs of having everything be natural and vegan. Our shop will be going live in a few months. Feel free to subsribe to our news letter to be the first to learn our release date.</p>
            </div>
        </div>

        <div class="col-about-3">
            <h1>Our Standards</h1>
            <div class="short-summ">
                <p>We strongly believe that everything humans eat should be natural. And just like our ancestors we are confident that nature can heal our bodies. Medicine is important and it's made great strides recently but only nature has the power to reverse the effects of illness. How long until everyone realizes this. We don't know. This is the future follow us on this adventure.</p>
            </div>
        </div>
        
    </div>
</div>

<!-- whats new with us section -->
<div class="why-happy">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <div class="sqaure-s">
                    <div class="text">
                        <h1>10500+</h1>
                        <h4>Customers</h4>

                    </div>
                    
                </div>
                <div class="sqaure-m">
                    <div class="text m">
                        <h1>8000+</h1>
                    <h4>Trips</h4>

                    </div>
                    
                </div>
                <div class="sqaure-l">
                    <div class="text l">
                        <h1>500+</h1>
                        <h4>Locations</h4>

                    </div>
                    
                </div>
                

            </div>
            <div class="col-2 padding-left">
                <div class="center">
                    <h1>we love our Customers</h1>
                    
                </div>
                <p>Booking through us will guarantee that all our customers are offered exceptional customer service year round. We have many customer reviews, and always receive great feedback from our diverse clientele. We enjoy making your comfort our priority. Our locations all around the world have been reviewed by many of our certified team members to ensure that all the apartments are clean and look amazing for the next guest. We pride ourselves in being globally recognized as one of the best travel agencies and we will continue to make that our priority. We can continue to prioritize your comfort thanks to many of our partners. You are invited to read the Blog page of this website where many travel bloggers post their experiences. They also make many recommendations to great restaurants that can be found minutes away from any of our houses. Thank you for booking with Valencia and enjoy your stay overseas. 
                </p>
                <a class="butt width-butt" href="#">Read More</a>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

store/templates/store/contact.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}


<style>
  .new-fun-city{
      padding: 10px;
      align-items: center !important;
      text-align: center !important;
      width: max-content !important;
      justify-content: center !important;
      align-content: center !important;
      align-self: center;
      margin: auto;
      width: max-content;
  }
  .form-area{
      text-align: center !important;
      min-width: 300px;
      max-width: max-content;
      padding: 10px;
  
  }
  .main-from-tit h1{
      text-align: center;
      font-size: 20px;
      font-weight: 600;
  
  }
  .input-box{
      width: max-content;
  
  }
  .input-box label{
      font-size: 20px;
  }
  .input-box input{
    border: 1px solid;
    border-color: rgb(17 33 17);
    border-radius: 10px;
    background-color: rgb(255 255 255);
    padding: 10px 15px;
    font-size: 18px;
    letter-spacing: 1px;
    margin: 10px;
    width: 300px;
  }
  .submit-butt{
      background-color: rgb(134, 189, 120);
      border: none;
      text-decoration: none;
      padding: 10px 15px;
      border-radius: 10px;
      width: 100px;
      margin: 15px;
      font-size: 18px !important;
      letter-spacing: 1px;
      transition: 0.5s;
  }
  .submit-butt:hover{
      background-color: rgb(53, 109, 63);
      color: #fff;
  }
  
  .go-back{
      background-color: rgb(151, 135, 135);
      border-radius: 10px;
      width: 150px;
      text-align: center;
  }
  .go-back button{
      padding: 10px 15px;
      background-color: rgb(151, 135, 135);
      border: none;
      text-decoration: none;
      color: #fff;
      letter-spacing: 1px;
      width: 150px;
      border-radius: 10px;
  
  }
  .go-back button:hover{
      background-color:rgb(99, 85, 85) ;
  }
  </style>



<div class="welcome-page">
  <div class="welcome-title">
    <h1>Contact us</h1>
    
  </div>



  <div class="new-fun-city">
   
    <div class="form-area">
      <div class="form-sec">
        <form method="post">

          {% csrf_token %}
    
         
    
            <div class="input-box" style="padding: 15px;">
              <label for="id_name"> </label>
              <input id="id_name" type="text" name="name" placeholder="Full Name">
            </div>
    
            <div  class="input-box" style="padding: 15px;">
              <label style="padding-left: 2rem;"  for="id_subject"></label>
              <!-- <input id="id_subject" type="options" name="subject"> -->
              <select name="subject" id="id_subject">
                <option value="Questions">Questions</option>
                <option value="Book Consulation">Book Consulation</option>
                <option value="Request More Reviews">Request More Reviews</option>
                <option value="Contact a Specialist">Contact a Specialist</option>
                <option value="Bussiness Inquery">Bussiness Inquery</option>
    
    
              </select>
            </div>
    
            <div class="input-box" style="padding: 15px;">
              <label for="id_sender"> </label>
              <input id="id_sender" type="email" name="sender" placeholder="Your Email">
            </div>
    
          <div class="add-space">
            <input class="submit-butt" type="submit" value="Submit">
          </div>
          <div class="butt-center">
            <div class="custom-butt"><a href="{% url 'login' %}">Login To Your Account</a></div>
          </div>
        </form>
        
      </div>
      
     
    </div>
  </div>


</div>




{% endblock content %}

store/templates/store/dashboard.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}

{% comment %} <h2>Welcome back {{ request.user|title }} !</h2> {% endcomment %}
<div class="dashboard" style="height: 80vh;">
  <div class="small-container">
    <div class="name-w" style="text-align: center;">
      <h1 style="padding-bottom: 50px;" style="padding-top: 80px;" >Welcome  {{ request.user|title }} </h1>
      <form method="post" action="">
        {% csrf_token %}
        
        <input style="padding-top: 20px;" style="padding-bottom: 20px;" class="submit-butt" type="submit" value="Logout">
        {% comment %} <input type="submit" value="Logout"> {% endcomment %}
    </form>
    </div>
  </div>
</div>


{% endblock content %}

store/templates/store/login.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}

<style>
  .new-fun-city{
      padding: 10px;
      align-items: center !important;
      text-align: center !important;
      width: max-content !important;
      justify-content: center !important;
      align-content: center !important;
      align-self: center;
      margin: auto;
      width: max-content;
  }
  .form-area{
      text-align: center !important;
      min-width: 300px;
      max-width: max-content;
      padding: 10px;
  
  }
  .main-from-tit h1{
      text-align: center;
      font-size: 20px;
      font-weight: 600;
  
  }
  .input-box{
      width: max-content;
  
  }
  .input-box label{
      font-size: 20px;
  }
  .input-box input{
    border: 1px solid;
    border-color: rgb(17 33 17);
    border-radius: 10px;
    background-color: rgb(255 255 255);
    padding: 10px 15px;
    font-size: 18px;
    letter-spacing: 1px;
    margin: 10px;
    width: 300px;
  }
  .submit-butt{
      background-color: rgb(134, 189, 120);
      border: none;
      text-decoration: none;
      padding: 10px 15px;
      border-radius: 10px;
      width: 100px;
      margin: 15px;
      font-size: 18px !important;
      letter-spacing: 1px;
      transition: 0.5s;
  }
  .submit-butt:hover{
      background-color: rgb(53, 109, 63);
      color: #fff;
  }
  
  .go-back{
      background-color: rgb(151, 135, 135);
      border-radius: 10px;
      width: 150px;
      text-align: center;
  }
  .go-back button{
      padding: 10px 15px;
      background-color: rgb(151, 135, 135);
      border: none;
      text-decoration: none;
      color: #fff;
      letter-spacing: 1px;
      width: 150px;
      border-radius: 10px;
  
  }
  .go-back button:hover{
      background-color:rgb(99, 85, 85) ;
  }
  </style>



<div class="welcome-page" style="height: max-content;">
  <div class="welcome-title">
    <h1>Login</h1>
    
  </div>

  <div class="new-fun-city">
    <div class="go-back">
      <a href="{% url 'index' %}"><button>Go Back</button></a>
    </div>
    <div class="form-area">
      <div class="main-form-tit">
        <h1>Login</h1>
      </div>
      <div class="form-sec">
        <form method="post">

          {% csrf_token %}
          
  
          <div class="input-box" style="padding: 15px;">
            <label for="id_username"> </label>
            <input id="id_username" type="text" name="username" placeholder="Username" required>
          </div>
          <div class="input-box" style="padding: 15px;">
            <label for="id_password"> </label>
            <input id="id_password" type="password" name="password" placeholder="Password" required>
          </div>
  
          <!-- <p><label for="id_subject">Subject:</label>
      <input id="id_subject" type="text" name="subject" maxlength="100" required></p> -->
  
        <input style="padding-top: 20px;" class="submit-butt" type="submit" value="Submit">
        <p>Don't Have an Account?</p>
        <div class="butt-center" style="padding-top: 20px;">
          <div class="custom-butt">
          <a href="{% url 'signup' %}">Register</a></div>
          
        </div>
        
      </form>
      </div>
      
     
    </div>
  </div>



</div>




{% endblock content %}

store/templates/store/register.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}

<style>
  .new-fun-city{
      padding: 10px;
      align-items: center !important;
      text-align: center !important;
      width: max-content !important;
      justify-content: center !important;
      align-content: center !important;
      align-self: center;
      margin: auto;
      width: max-content;
  }
  .form-area{
      text-align: center !important;
      min-width: 300px;
      max-width: max-content;
      padding: 10px;
  
  }
  .main-from-tit h1{
      text-align: center;
      font-size: 20px;
      font-weight: 600;
  
  }
  .input-box{
      width: max-content;
  
  }
  .input-box label{
      font-size: 20px;
  }
  .input-box input{
    border: 1px solid;
    border-color: rgb(17 33 17);
    border-radius: 10px;
    background-color: rgb(255 255 255);
    padding: 10px 15px;
    font-size: 18px;
    letter-spacing: 1px;
    margin: 10px;
    width: 300px;
  }
  .submit-butt{
      background-color: rgb(134, 189, 120);
      border: none;
      text-decoration: none;
      padding: 10px 15px;
      border-radius: 10px;
      width: 100px;
      margin: 15px;
      font-size: 18px !important;
      letter-spacing: 1px;
      transition: 0.5s;
  }
  .submit-butt:hover{
      background-color: rgb(53, 109, 63);
      color: #fff;
  }
  
  .go-back{
      background-color: rgb(151, 135, 135);
      border-radius: 10px;
      width: 150px;
      text-align: center;
  }
  .go-back button{
      padding: 10px 15px;
      background-color: rgb(151, 135, 135);
      border: none;
      text-decoration: none;
      color: #fff;
      letter-spacing: 1px;
      width: 150px;
      border-radius: 10px;
  
  }
  .go-back button:hover{
      background-color:rgb(99, 85, 85) ;
  }
  </style>



<div class="welcome-page">
  <div class="welcome-title">
    <h1>Register Here</h1>
    
  </div>



  <div class="new-fun-city">
    <div class="go-back">
      <a href="{% url 'index' %}"><button>Go Back</button></a>
    </div>
    <div class="form-area">
      <div class="main-form-tit">
        <h1>Register</h1>
      </div>
      <div class="form-sec">
        <form method="post">
            
            {% csrf_token %}
        
            <div class="input-box" style="padding: 15px;">
              <label for="id_username"></label>
              <input id="id_username" type="text" name="username" placeholder="Username">
            </div>
            <div class="input-box" style="padding: 15px;">
              <label for="id_first_name"></label>
              <input id="id_first_name" type="text" name="first_name" placeholder="First Name">
            </div>
            <div class="input-box" style="padding: 15px;">
              <label for="id_last_name"></label>
              <input id="id_last_name" type="text" name="last_name" placeholder="Last Name">
            </div>
            <div class="input-box" style="padding: 15px;">
              <label for="id_email"></label>
              <input id="id_email" type="email" name="email" placeholder="Email">
            </div>
            <div class="input-box" style="padding: 15px;">
              <label for="id_password1"></label>
              <input id="id_password1" type="password" name="password1" placeholder="Password">
            </div>
            <div class="input-box" style="padding: 15px;">
              <label for="id_password2"></label>
              <input id="id_password2" type="password" name="password2" placeholder="Re-enter Password">
            </div>
             
    
          <input class="submit-butt" type="submit" >
          <p>Have an Account?</p>
          <div class="butt-center">
            <div class="custom-butt"><a href="{% url 'login' %}">Login</a></div>
          </div>
        </form>
      </div>
      
     
    </div>
  </div>


</div>


{% endblock content %}